apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: kafka-connectivity
  labels:
    catalog.testkube.io/category: messaging
    catalog.testkube.io/component: kafka
    catalog.testkube.io/validation-type: connectivity
  annotations:
    catalog.testkube.io/display-name: "Kafka Connectivity Check"
    catalog.testkube.io/description: "Validates Kafka broker connectivity, topic listing, and basic produce/consume operations"
    catalog.testkube.io/icon: "https://cdn.simpleicons.org/apachekafka"
    catalog.testkube.io/tags: "kafka,messaging,connectivity,broker,streaming"

spec:
  config:
    bootstrap_servers:
      type: string
      default: "kafka.default.svc.cluster.local:9092"
      description: "Kafka bootstrap servers (comma-separated)"
    security_protocol:
      type: string
      default: "PLAINTEXT"
      description: "Security protocol (PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL)"
    test_topic:
      type: string
      default: "testkube-validation"
      description: "Topic name for produce/consume test (will be auto-created if allowed)"

  steps:
  - name: "Validate Kafka Connectivity"
    run:
      image: docker.io/apache/kafka:4.1.1@sha256:0bc1bb2478f45b6cea78864df86acdc11e8df2c5172477819a4d12942cbe5d40
      shell: |
        echo "============================================"
        echo "  Kafka Connectivity Validation"
        echo "============================================"
        echo ""
        echo "Bootstrap Servers: {{ config.bootstrap_servers }}"
        echo "Security Protocol: {{ config.security_protocol }}"
        echo "Test Topic: {{ config.test_topic }}"
        echo ""

        # Common arguments
        KAFKA_ARGS="--bootstrap-server {{ config.bootstrap_servers }}"

        # Test 1: Broker connectivity via metadata
        echo ">>> Test 1: Broker Connectivity"
        if kafka-broker-api-versions.sh $KAFKA_ARGS > /dev/null 2>&1; then
          echo "✓ Successfully connected to Kafka brokers"
        else
          echo "✗ Failed to connect to Kafka brokers"
          kafka-broker-api-versions.sh $KAFKA_ARGS 2>&1 || true
          exit 1
        fi
        echo ""

        # Test 2: List topics
        echo ">>> Test 2: List Topics"
        TOPICS=$(kafka-topics.sh $KAFKA_ARGS --list 2>/dev/null)
        TOPIC_COUNT=$(echo "$TOPICS" | grep -c "." || echo "0")
        echo "✓ Found $TOPIC_COUNT topic(s)"
        if [ -n "$TOPICS" ]; then
          echo "  Topics: $(echo $TOPICS | tr '\n' ', ' | sed 's/,$//')"
        fi
        echo ""

        # Test 3: Describe cluster
        echo ">>> Test 3: Cluster Info"
        kafka-metadata.sh $KAFKA_ARGS --snapshot /tmp/meta --command "node" 2>/dev/null || \
          kafka-broker-api-versions.sh $KAFKA_ARGS 2>/dev/null | head -5
        echo ""

        # Test 4: Create test topic (if it doesn't exist)
        echo ">>> Test 4: Test Topic"
        if kafka-topics.sh $KAFKA_ARGS --list | grep -q "^{{ config.test_topic }}$"; then
          echo "✓ Test topic '{{ config.test_topic }}' exists"
        else
          echo "  Creating test topic '{{ config.test_topic }}'..."
          if kafka-topics.sh $KAFKA_ARGS --create --topic {{ config.test_topic }} --partitions 1 --replication-factor 1 2>/dev/null; then
            echo "✓ Test topic created"
          else
            echo "⚠ Could not create test topic (may require admin permissions)"
            echo "  Skipping produce/consume test"
            echo ""
            echo "============================================"
            echo "  ✓ Kafka Basic Connectivity Passed"
            echo "============================================"
            exit 0
          fi
        fi
        echo ""

        # Test 5: Produce message
        echo ">>> Test 5: Produce Message"
        TEST_MESSAGE="testkube-validation-$(date +%s)"
        echo "$TEST_MESSAGE" | kafka-console-producer.sh $KAFKA_ARGS --topic {{ config.test_topic }} 2>/dev/null
        echo "✓ Message produced: $TEST_MESSAGE"
        echo ""

        # Test 6: Consume message
        echo ">>> Test 6: Consume Message"
        CONSUMED=$(timeout 10 kafka-console-consumer.sh $KAFKA_ARGS \
          --topic {{ config.test_topic }} \
          --from-beginning \
          --max-messages 1 \
          --timeout-ms 5000 2>/dev/null | tail -1)

        if [ -n "$CONSUMED" ]; then
          echo "✓ Message consumed: $CONSUMED"
        else
          echo "⚠ No message consumed (topic may be empty or consumer timeout)"
        fi
        echo ""

        echo "============================================"
        echo "  ✓ Kafka Connectivity Validation Passed"
        echo "============================================"
